### ISSUE TITLE
Time.range documentation

### ISSUE THREAD

**Issue by takje** [NREL/rplexos#12]
When using large databases, it is difficult to get them in the memory as a whole. Therefore, I would like to subset my Plexos solution using rplexos. However, I can't get the most important subset item, time.range, to work.

On my own db, I tried the following command:
`PASA <- query_interval(db,"Generator",c("Installed Capacity"),phase=2, time.range=c('2014-01-01 0:00:00','2014-12-31 00:00:00'))`

However, I get the error:
`Error in UseMethod("escape") : 
  no applicable method for 'escape' applied to an object of class "c('POSIXct', 'POSIXt')"`

I tried some variations such as: `time.range=c('2014-01-01','2014-12-31')` OR `time.range=c('20140101','20141231')`, however the error keeps coming back.

The traceback looks like this:
```
    46: escape(val, con = con)
    45: FUN(X[[3L]], ...)
    44: vapply(dots(...), escape_expr, character(1))
    43: build_sql(x, " BETWEEN ", left, " AND ", right)
    42: between(time, 1388534400, 1419984000)
    41: eval(expr, envir, enclos)
    40: eval(x, envir = env)
    39: FUN(X[[2L]], ...)
    38: lapply(expr, function(x) {
            if (is.atomic(x)) 
                return(escape(x, con = con))
            env <- sql_env(x, variant, con, window = window)
            eval(x, envir = env)
        })
    37: translate_sql_q(expr, tbl = x, env = NULL, ...)
    36: translate(x$where)
    35: build_query(object)
    34: update.tbl_sql(.data, where = c(.data$where, input))
    33: update(.data, where = c(.data$where, input))
    32: update(.data, where = c(.data$where, input))
    31: filter_.tbl_sql(.data, .dots = lazyeval::lazy_dots(...))
    30: filter_(.data, .dots = lazyeval::lazy_dots(...))
    29: filter(., between(time, time.r.min, time.r.max))
    28: function_list[[k]](value)
    27: withVisible(function_list[[k]](value))
    26: freduce(value, `_function_list`)
    25: `_fseq`(`_lhs`)
    24: eval(expr, envir, enclos)
    23: eval(quote(`_fseq`(`_lhs`)), env, env)
    22: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
    21: time.data %>% filter(between(time, time.r.min, time.r.max))
    20: query_master_each(x$db, ...)
    19: safe_query(., time, .$collection, .$property, new$columns, new$time.range, 
            filter, phase)
    18: eval(expr, envir, enclos)
    17: eval(args[[j]]$expr, envir = env)
    16: do_.rowwise_df(.data, .dots = lazyeval::lazy_dots(...))
    15: do_(.data, .dots = lazyeval::lazy_dots(...))
    14: do(., safe_query(., time, .$collection, .$property, new$columns, 
            new$time.range, filter, phase))
    13: function_list[[k]](value)
    12: withVisible(function_list[[k]](value))
    11: freduce(value, `_function_list`)
    10: `_fseq`(`_lhs`)
    9: eval(expr, envir, enclos)
    8: eval(quote(`_fseq`(`_lhs`)), env, env)
    7: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
    6: db.prop %>% rowwise() %>% do(safe_query(., time, .$collection, 
           .$property, new$columns, new$time.range, filter, phase))
    5: query_master(db, "interval", ...)
    4: query_interval(db, "Generator", c("Installed Capacity"), phase = Phase_id, 
           time.range = c("20140101", "20141231"))
    3: eval(expr, envir, enclos)
    2: eval(lhs, parent, parent)
    1: query_interval(db, "Generator", c("Installed Capacity"), phase = Phase_id, 
           time.range = c("20140101", "20141231"))
```

The problem is that since my db spans many years, it has not enough memory to load all the years. Am I using the time.range feature wrong? In that case could you add a working example of time.range?

Btw, wonderful package! It's really helpful that you put your time and effort in developing this.

**Comment by eibanez** [comment]
Can you try using double quotes? The following works for me:

```
b <- query_interval(d, "Generator", "Net Generation",
  time.range = c("2020-04-01", "2020-04-03"))
```

**Comment by takje** [comment]
I tried
`PASA <- query_interval(db,"Generator",c("Installed Capacity"),phase=Phase_id, time.range=c("2014-02-02", "2014-03-03"))`
But it gave exactly the same error

If you look at traceback 42, you can see that my dates are transferred well, which can be checked with:
```
as.POSIXct(1388534400, origin='1970-01-01 00:00:00')
as.POSIXct(1419984000, origin='1970-01-01 00:00:00')
```

However, it is the time vector format where he complains about. It seems that it goes wrong when he tries to convert this to the SQL code. Any suggestions for new tests? :-)

**Comment by eibanez** [comment]
What is the output of `sessionInfo()`?

**Comment by eibanez** [comment]
Also, are you able to build the package from Github? I might have a quick fix for you to try.

**Comment by eibanez** [comment]
Ok. I think I found a possible solution here: https://github.com/hadley/dplyr/issues/857

Can you run the following before your query?

```
escape.POSIXt <- dplyr:::escape.Date
```

**Comment by takje** [comment]
Yeah, that last line solved the problem! Thanks a lot for the quick reply and fix.

**Comment by eibanez** [comment]
Glad it did. I'm going to add that line to the package, until it gets fixed in dplyr.

**Comment by takje** [comment]
I updated the version, but it still doesn't work without adding the line:
`escape.POSIXt <- dplyr:::escape.Date` myself. Could it be that the location where he reads the code is not processed?

**Comment by eibanez** [comment]
I know what happened. I'll fix it.

**Comment by takje** [comment]
Thanks!

**Comment by eibanez** [comment]
@takje: The last commit should fix it. Let me know if it still doesn't work after the next release (you can also build from the repo if you know how).

**Comment by eibanez** [comment]
@takje Could you try if the newest version works for you? I'd like to get this working before the next CRAN submission. You can download the latest binary using the following commands:

```
download.file("http://ci.appveyor.com/api/buildjobs/tootmnh92b5yg4v8/artifacts/rplexos_0.12.1.99.zip", "rplexos_0.12.1.99.zip")
install.packages("rplexos_0.12.1.99.zip")
```

**Comment by takje** [comment]
I tried:
```
> download.file("http://ci.appveyor.com/api/buildjobs/tootmnh92b5yg4v8/artifacts/rplexos_0.12.1.99.zip", "~/rplexos_0.12.1.99.zip")
> install.packages("~/rplexos_0.12.1.99.zip")
```
It gives an error when I load the package since I have an older r version, but sessionInfo() shows that I have RPlexos installed and loaded:

```
> require(rplexos)
Loading required package: rplexos
Warning message:
package ‘rplexos’ was built under R version 3.2.0 

> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] tcltk     stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] gWidgetstcltk_0.0-55 digest_0.6.8         gWidgets_0.0-54      data.table_1.9.4    
 [5] R.utils_1.34.0       R.oo_1.18.0          R.methodsS3_1.6.1    lubridate_1.3.3     
 [9] dplyr_0.4.1          reshape2_1.4.1       ggplot2_1.0.0        installr_0.15.3     
[13] rplexos_0.12.1.99   

loaded via a namespace (and not attached):
 [1] assertthat_0.1   chron_2.3-45     colorspace_1.2-4 DBI_0.3.1        grid_3.1.2      
 [6] gtable_0.1.2     lazyeval_0.1.10  magrittr_1.5     MASS_7.3-37      memoise_0.2.1   
[11] munsell_0.4.2    parallel_3.1.2   plyr_1.8.1       proto_0.3-10     R6_2.0.1        
[16] Rcpp_0.11.4      RSQLite_1.0.0    scales_0.2.4     stringr_0.6.2    tools_3.1.2
```

However, when I try to do a query, I still get an error.

**Comment by eibanez** [comment]
Ok, tried a different solution. Does this work?

```
download.file("http://ci.appveyor.com/api/buildjobs/98rc9w4hp4yem44h/artifacts/rplexos_0.12.1.99.zip", "~/rplexos_0.12.1.99.zip")
install.packages("~/rplexos_0.12.1.99.zip")
```

**Comment by takje** [comment]
While the package depends on the package foreach now
```
> prices <- query_interval(db,"Region","Price",phase=3,c("name"),time.range=c("2015-01-01 00:00:00","2015-12-31 23:00:00"))
Error in loadNamespace(name) : there is no package called ‘foreach’
```

It works when I load that package. Without using the line 
```
escape.POSIXt <- dplyr:::escape.Date
```

**Comment by eibanez** [comment]
Great! I'll close this for good then.

I'm implementing parallel queries, that's the reason for the new dependency.

**Comment by takje** [comment]
Super, looking forward. How is it going to work? Parallel queries when I query for multiple properties using one single command?

**Comment by eibanez** [comment]
It will allow to query multiple databases at once. It's especially useful when you divide a long simulation or are comparing multiple cases.

**Comment by peterparkerspicklepatch** [comment]
I'm still having this problem only it's manifested as `Error in UseMethod("escape") : 
  no applicable method for 'escape' applied to an object of class "function"`
