### ISSUE TITLE
Filtering query

### ISSUE THREAD

**Issue by rtosetto** [NREL/rplexos#15]
Hello,
Thanks for the very useful package! It's helping us a lot.

Apparently the filter parameter in query_interval does not work when no time.range is specified.
Looking at the code it seems indeed that the filter_rplexos is not called if is.null(time.range).

Cheers,
Riccardo

**Comment by eibanez** [comment]
I'll look into it, but it might take me a while. Feel free to take a stab at it if you feel comfortable.

**Comment by takje** [comment]
I goes wrong in the function `query_master_each` in query.R.

At line 352-359, you have an if check to see if time.range is used. The filtering is in the same if, while it should be outside the if (to avoid that it is ignored when there is no time.range).

**Comment by eibanez** [comment]
I see...

Looks like an easy fix then.
