### ISSUE TITLE
Issue with dev version of dplyr

### ISSUE THREAD

**Issue by hadley** [NREL/rplexos#37]
The unit tests fail with the development version of dplyr. Could you please take a look?

**Comment by hadley** [comment]
The most likely cause is that dplyr 0.4.2 now doesn't object when you give it columns with attributes, instead doing it's best to preserve them

**Comment by eibanez** [comment]
I will take a look. Thanks for the heads up, Hadley.

**Comment by eibanez** [comment]
Fixed! I will include this in a future submission

**Comment by hadley** [comment]
Thanks! Do you think you could submit this week? I'd like to get this version of dplyr to CRAN

**Comment by eibanez** [comment]
I can do that. I'll submit by Friday at the latest.

**Comment by eibanez** [comment]
@hadley, the revised version has been accepted to CRAN.
