### ISSUE TITLE
db file sizes

### ISSUE THREAD

**Issue by takje** [NREL/rplexos#38]
Hi Eibanez,

When doing some big runs, I end up with Plexos solution files (.zip) that have a size of 900MB. Converting these to Plexos db files yields db files with a size of more than 5GB. Then I cancelled a lot of the reporting settings and now I have solution files of approximately 100MB. However, the Plexos db is still over 3GB in size. Since I decreased the size of the Plexos output file with a factor 9, I would expect that the db size also shrinks with a factor nine. In reality this is not even a factor 2. Could it be that he still saves all the tables in the db, although they all are empty?

Regards,
Jef

**Comment by eibanez** [comment]
There is some optimization in the way that some results are saved. It's possible that the "extra" reports that you are canceling are more efficient because of this.
