### ISSUE TITLE
Query Master Filters

### ISSUE THREAD

**Issue by BenjaminWatts** [NREL/rplexos#39]
This is such a great package - it makes my life so much easier!

One thing I am trying to do at the moment is to pass filters dynamically to a query_master command, using the shiny app.

So I have a character vector in R with a list of the names of Generators or regions. Sometimes this will contain some values, sometimes it will be empty. 

I'd like to pass this to a query master command and slot it in where the asterixs are.

query_master(db, time.range = daterange, time = input$TimePeriod, prop = input$Property, phase = phase, col = input$Collection, filter = *****())

Is there a simple way to do this? I've tried playing around with wildcards, and parsing text, but can't find a solution to what seems like it should be really simple!

**Comment by eibanez** [comment]
Use `filter = list(name = YourCharacterVector)`

**Comment by BenjaminWatts** [comment]
Thanks ever so much - is there a wildcard I can use in place of  "YourCharacterVector"?

**Comment by eibanez** [comment]
No, if you apply the filter you should have a vector with the actual strings that you want to use. If you don't want to apply that filter, I would check your vector first and apply a query with or without the filter.

**Comment by BenjaminWatts** [comment]
Ah OK no worries.  Thanks!
