### ISSUE TITLE
issues with plexos_open for input files

### ISSUE THREAD

**Issue by smith242** [NREL/rplexos#40]
Hi there I'm having some trouble opening input files. rplexos is processing the folder and creating the database file but when I try to open using plexos_open I get the following error:

Error: No databases found in the list of folders. 
Did you forget to use process_folder()?

This seems to work fine for the solution file but not for the input. Can you please let me  know what I'm doing wrong? 

Following this, I'm trying to access the time horizon settings in the input file if you could also let me know how I can do this? 

Thanks

**Comment by eibanez** [comment]
rplexos only converts the input database to SQLite. You will have to come up with any queries you want on your own.
