### ISSUE TITLE
Query Specific Scenario

### ISSUE THREAD

**Issue by BenjaminWatts** [NREL/rplexos#41]
Is there an easy way of querying a specific, or a few scenarios 

Imagine something like this

query_year(db, Generator, Generation, filter = list(scenario = "High Wind")...

OR

query_year(db, Generator, Generation, filter = list(scenario =c("Low Wind", "High Wind"))...

**Comment by eibanez** [comment]
You can subset `db` first and then query.

**Comment by BenjaminWatts** [comment]
Hey -- thanks for this suggestion. What command would you use to subset the db - when I try using subset(db, scenario == x) or db[,1] then I the Type becomes tbl_df instead of rplexos, and so query_year rejects it?

**Comment by eibanez** [comment]
try doing the following after subsetting:
```
class(subset.db) <- class(db)
```
