### ISSUE TITLE
Warning: Log in solution did not parse correctly.

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/rplexos#49]
base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### *\* Examples
# Process the folder with the solution file provided by rplexos

location <- location_solution_rplexos()
process_folder(location)
Warning: Log in solution '/home/hornik/tmp/CRAN/rplexos.Rcheck/rplexos/extdata/solution/Model_Base_Solution.zip' did not parse correctly.
    Data parsed correctly if no other errors were found.

**Comment by danielsjf** [comment]
I didn't solve the error, but I removed all the references to it in the building/testing of the package by CRAN. Something changed in the input files part. For some reason this fails currently. This gives an error so I removed all the examples and tests related to this.

At the moment, I get three errors when I test the package. These are all three in skip_on_cran() parts. This shouldn't be a problem.

Apart from this, the check is successful and the submission to CRAN should be fine. Let me know if it works.
