### ISSUE TITLE
Fix dependencies for RSQLite > 1.1

### ISSUE THREAD

**Issue by danielsjf** [NREL/rplexos#55]
New version broke rplexos

**Comment by danielsjf** [comment]
Fixed with commit 7416bc4f07d495ac9c95202ab48df2dd1f5d69f6

**Comment by danielsjf** [comment]
@claytonpbarrows I've recently done some modifications to update the rplexos package. A full list of the updates is in news.md. Would it be possible to update the CRAN version? If not, I am always willing to take over the CRAN maintainer role.

**Comment by claytonpbarrows** [comment]
@danielsjf You have my permission to takeover the CRAN maintainer role. I'm currently unable to devote any time to this.
