### ISSUE TITLE
'process_folder' crashes with Plexos 7.5 solution file

### ISSUE THREAD

**Issue by monnedepraetere** [NREL/rplexos#64]
I have used rplexos extensively to extract results files created by Plexos 7.3. (Thanks for developing this very useful package!) While trying to run `process_folder` on results of a 7.5 model run, I get the following error:

`Error in { : task 1 failed - "no such column: p.year"`

It seems like the database structure has changed between 7.3 and 7.5 and that may trip up rplexos? Note that I am running rplexos version `1.1.12` and r version `3.4.1` on a windows machine.

**Comment by monnedepraetere** [comment]
Update: I now encountered the same issue while processing solutions from Plexos 7.3, so it seems like this is not an upgrade issue. More likely, it seems like we are reporting additional properties that rplexos can't process. Will report back once we found out more.

**Comment by danielsjf** [comment]
Yes this has been an issue since a while. It is solved. Are you using the latest version from Github?

**Comment by danielsjf** [comment]
To be really precise, this commit solved it 4a674090bce937e206db17ad897cd2f934ff5b17

Therefore it happened since 7.5R01

**Comment by monnedepraetere** [comment]
Thanks so much @danielsjf, that indeed solved it!
